[package]
name = "material-verification"
version = "0.1.0"
edition = "2021"

[dependencies]
material-verification-lib = { path = "../lib" }
pico-sdk = { git = "https://github.com/brevis-network/pico" }
serde = { version = "1.0", features = ["derive"] }