services:
  pico-development:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      # Mount specific directories individually to avoid conflicts
      - ./:/project
      - ../verification-app:/project/verification-app 
    environment:
      - RUST_BACKTRACE=1
    stdin_open: true
    tty: true