services:
  pico-development:
    build:
      context: ../
      dockerfile: pico-verification/dockerfile
    volumes:
      - ./:/project/pico-verification
      - ../verification-app:/project/verification-app
      - ./output:/project/output
    environment:
      - RUST_BACKTRACE=1
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true