services:
  pico-development:
    build:
      context: ../
      dockerfile: pico-verification/dockerfile
    volumes:
      - ./:/project
      - ../verification-app:/project/verification-app 
      - ../pico-verification:/project/pico-verification
    environment:
      - RUST_BACKTRACE=1
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true