FROM rust:latest

# Install dependencies
RUN apt-get update && \
    apt-get install -y git build-essential

# Install specific nightly version required by Pico
RUN rustup install nightly-2024-11-27 && \
    rustup default nightly-2024-11-27 && \
    rustup component add rust-src --toolchain nightly-2024-11-27

# Clone Pico repo and install CLI
WORKDIR /tmp
RUN git clone https://github.com/brevis-network/pico
WORKDIR /tmp/pico/sdk/cli
RUN cargo install --locked --force --path .

# Set default working directory 
WORKDIR /project

# Keep container running
CMD ["bash", "-c", "tail -f /dev/null"]