#!/bin/bash

# Script to set up environment variables for local development

# Check if .env.local exists
if [ -f .env.local ]; then
  echo "Found existing .env.local file"
  
  # Check if the environment variables need to be updated
  if grep -q "localhost" .env.local; then
    echo "Environment variables need to be updated with your network IP"
  else
    echo "Environment variables already set with network IP"
    echo "Current settings:"
    cat .env.local
    echo "To force update, delete .env.local first"
    exit 0
  fi
else
  echo "Creating new .env.local file"
fi

# Get local IP address (Mac friendly)
LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n 1)

if [ -z "$LOCAL_IP" ]; then
  echo "Could not detect local IP address"
  echo "Using localhost as fallback"
  LOCAL_IP="localhost"
else
  echo "Detected local IP: $LOCAL_IP"
fi

# Create .env.local file with the local IP
cat > .env.local << EOF
# Auto-generated by setup script - $(date)./setup-dev.sh
NEXT_PUBLIC_API_URL=http://${LOCAL_IP}:3001
NEXT_PUBLIC_BACKEND_URL=http://${LOCAL_IP}:3000
EOF

echo ".env.local created with your network IP addresses"
echo "Contents:"
cat .env.local
echo ""
echo "Now starting the development server..."
echo "To share, make sure ports 3000 and 3001 are allowed through your firewall"
